### ISSUE TITLE
running examples and get error:  type object 'cublasLt' has no attribute 'cublasLtHandle_t'

### ISSUE THREAD

**Issue by qiufengyuyi** [OpenBMB/BMInf#11]
when running examples/fill_blank.py, get error:
AttributeError: type object 'cublasLt' has no attribute 'cublasLtHandle_t'

cuda version is 10.0
have successfully installed bminf 0.4.0
any idea how to solve this problem?

**Comment by qiufengyuyi** [comment]
I found cublasLt is supported by cuda >=10.1
so the latest code does not support cuda 10.0?

**Comment by a710128** [comment]
Yes. CUDA 10.0 is not supported.

**Comment by qiufengyuyi** [comment]
> Yes. CUDA 10.0 is not supported.
fine.... i think you should add this requirement to the readme and docs related
