### ISSUE TITLE
cublas error: CUBLAS_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by huhk-sysu** [OpenBMB/BMInf#13]
运行examples/generate.py时报错，上层调用栈是functions/gemm.py的第249行。
https://github.com/OpenBMB/BMInf/blob/d40c6f5d5678e1cba771048ecd0923bceae176e2/bminf/functions/gemm.py#L249

使用的环境为：
cuda 10.1（cublas版本为10.1.0.63）
BMInf 0.0.4 通过clone + python setup.py install方式安装
torch 1.7.1

**Comment by a710128** [comment]
请提供一下GPU型号。

**Comment by huhk-sysu** [comment]
> 请提供一下GPU型号。
目前使用的是Tesla M40，有需要我可以更换其他型号的显卡尝试
