### ISSUE TITLE
generate.py示例程序错误

### ISSUE THREAD

**Issue by huhk-sysu** [OpenBMB/BMInf#14]
在
https://github.com/OpenBMB/BMInf/blob/d40c6f5d5678e1cba771048ecd0923bceae176e2/examples/generate.py#L4-L21
中，函数设置了生成的`result`中含有`<eod>`后才停止。

但在
https://github.com/OpenBMB/BMInf/blob/d40c6f5d5678e1cba771048ecd0923bceae176e2/bminf/models/cpm1.py#L90-L99
中，采样出`<eod>`后循环终止，其未被加入到`ret`中，因此不会被解码出来，`result`中不可能含有`<eod>`。

因此，`generate.py`中实际会无限循环生成文本。

**Comment by a710128** [comment]
这样的设计，是因为我们希望在Demo中，模型可以无限的生成下去。
你可以暂时先参考我们的generate函数，实现一个自己的generate。我们会考虑在之后的版本完善生成相关接口，提供<EOD>相关控制支持。
