### ISSUE TITLE
请问CPM2.1模型所对应的vocab.txt哪里可以下载？

### ISSUE THREAD

**Issue by chenpe32cp** [OpenBMB/BMInf#25]
请问CPM2.1模型所对应的vocab.txt哪里可以下载？

**Comment by a710128** [comment]
https://github.com/TsinghuaAI/CPM-2-Pretrain/blob/master/bpe_cn/vocab.txt

**Comment by chenpe32cp** [comment]
> https://github.com/TsinghuaAI/CPM-2-Pretrain/blob/master/bpe_cn/vocab.txt

好的，感谢！

**Comment by chenpe32cp** [comment]
done
