### ISSUE TITLE
CUDA Error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by AdamBear** [OpenBMB/BMInf#29]
**Failed to run with P100 GPU which works fine with other pytorch cuda code, GPU info:**
GPU Device 0: "Pascal" with compute capability 6.0
Compute 6.0 CUDA device: [Tesla P100-PCIE-16GB]

**error trace:**
<pre>
/opt/conda/lib/python3.8/site-packages/cpm_kernels/library/cuda.py in checkCUStatus(error)
    214 def checkCUStatus(error : int) -> None:
    215     if error != CUDA_SUCCESS:
--> 216         raise RuntimeError("CUDA Error: %s" % cuGetErrorString(error))
    217 
    218 @cuda.bind("cuDriverGetVersion", [ctypes.POINTER(ctypes.c_int)], CUresult)

RuntimeError: CUDA Error: no kernel image is available for execution on the device
</pre>

**What the minimal compute version does cpm-kernels need?**

**Comment by a710128** [comment]
BMInf requires compute capability 6.1.  The description in the current documentation may inaccurate.

**Comment by AdamBear** [comment]
I see, thanks!
