### ISSUE TITLE
RuntimeError: CUBLAS error: CUBLAS_STATUS_EXECUTION_FAILED[BUG]

### ISSUE THREAD

**Issue by zhangxliang** [OpenBMB/BMInf#30]
**Describe the bug**

用的CPM-2提供的docker镜像，出现该bug，其他环境没有尝试。

**Minimal steps to reproduce**

**Expected behavior**

运行examples下面的generate以及quick start中的代码都报错

**Screenshots**

![image](https://user-images.githubusercontent.com/33020071/147736281-ed91e7d3-5f72-459f-909f-ba6fb4531ebf.png)

**Environment:**

![image](https://user-images.githubusercontent.com/33020071/147736466-3b836364-cbcd-4516-8de6-89f564549c1d.png)
![image](https://user-images.githubusercontent.com/33020071/147736516-c12e14bc-39c3-4786-8a92-de44f42a8533.png)

**Comment by a710128** [comment]
请反馈一下：适用的GPU型号，BMInf版本号，CUDA版本

**Comment by zhangxliang** [comment]
> 请反馈一下：使用的GPU型号，BMInf版本号，CUDA版本

GPU: GTX RTX 3090, BMInf: 1.0.0, CUDA: 11.1

**Comment by a710128** [comment]
试一下不用docker直接运行呢

**Comment by zhangxliang** [comment]
> 试一下不用docker直接运行呢

不用docker运行不会出现类似错误，具体原因不明，可能是docker中pytorch与cuda和显卡不兼容

**Comment by a710128** [comment]
可能是由于docker内的cuda版本与系统环境中的不一致
