### ISSUE TITLE
[FEATURE]允许加载本地模型

### ISSUE THREAD

**Issue by huhk-sysu** [OpenBMB/BMInf#36]
**Is your feature request related to a problem? Please describe.**

有时候跑模型的服务器是物理断网的，需要手动下载模型上传后再加载。
从前（0.0.4版本）可以通过设置config的MODEL_NAME实现本地加载，但代码更新到1.0.0以后不能这样做了（除非修改BMInf的源码）。

**Describe the solution you'd like**

在初始化模型时提供一个接口，指定本地路径进行加载（可能通过修改现有的`version`字段实现）。

**Describe alternatives you've considered**

无。

其他：请问0.0.4到1.0.0之间，CPM2.1模型是否更新过？使用1.0.0的代码加载0.0.4时期下载的模型时报错了。

**Comment by a710128** [comment]
BMInf在1.0.0版本中更新了模型的实现细节，因此CPM2.1的模型也更新了需要重新下载。

**Comment by a710128** [comment]
试一下BMInf 1.0.1
