### ISSUE TITLE
[FEATURE]How to finetune CPM2.1？

### ISSUE THREAD

**Issue by drxmy** [OpenBMB/BMInf#58]
I am not familiar with int8. But i suppose it can not be trained like other fp32 models? Any suggestion about how to finetune it?

And does cpm2.1 has any report or paper? I did not find it anywhere.

Thank you!

**Comment by a710128** [comment]
Int8 model cannot be trained like a float model. BMInf only supports prompt tuning which means parameter of the model is not trainable.

**Comment by drxmy** [comment]
Thank you!
