### ISSUE TITLE
[BUG] TypeError: object of type 'TransformerBlockList' has no len()

### ISSUE THREAD

**Issue by jiangliqin** [OpenBMB/BMInf#62]
**Describe the bug**
提示如上提示，是因为bminf问题吗？

<img width="1667" alt="image" src="https://user-images.githubusercontent.com/12250847/212636947-0e9e67c1-5eaf-44ed-8bad-1ad384d482ce.png">

**Comment by a710128** [comment]
目前BMInf的wrapper不能直接对bmtrain的DistributedModule生效，所以会出现以上的错误。
