### ISSUE TITLE
[BUG] eva2 = bminf.models.EVA2()

### ISSUE THREAD

**Issue by Hansen06** [OpenBMB/BMInf#9]
EVA报错

In [11]: eva2 = bminf.models.EVA2()
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-11-04bbda5275e9> in <module>()
----> 1 eva2 = bminf.models.EVA2()

~/anaconda3/envs/yhs/lib/python3.6/site-packages/bminf/models/eva2.py in __init__(self, device, memory_limit, config)
     56                     raise ValueError("Memory is not enough")
     57 
---> 58         super().__init__(config)
     59 
     60     def dialogue(self, 

~/anaconda3/envs/yhs/lib/python3.6/site-packages/bminf/arch/t5/model.py in __init__(self, config)
     73             vocab_path = data.ensure_file(config.MODEL_NAME, "vocab.txt")
     74 
---> 75             self.tokenizer = T5Tokenizer(vocab_path)
     76 
     77             self.device = config.DEVICE

~/anaconda3/envs/yhs/lib/python3.6/site-packages/bminf/arch/t5/tokenizer.py in __init__(self, vocab_path, max_len, max_sentinels)
     81         self.translator_dec = str.maketrans("\u2582\u2583", " \n")
     82 
---> 83         self.sentinel_list = [self.encoder['<s_{}>'.format(i)] for i in range(max_sentinels)]
     84 
     85     @property

~/anaconda3/envs/yhs/lib/python3.6/site-packages/bminf/arch/t5/tokenizer.py in <listcomp>(.0)
     81         self.translator_dec = str.maketrans("\u2582\u2583", " \n")
     82 
---> 83         self.sentinel_list = [self.encoder['<s_{}>'.format(i)] for i in range(max_sentinels)]
     84 
     85     @property

KeyError: '<s_0>'

**Comment by a710128** [comment]
请提供一下你的 bminf 的版本。
```console
$ python3 -c "import bminf;print(bminf.__version__)"
```

**Comment by Hansen06** [comment]
> 请提供一下你的 bminf 的版本。
> 
> ```
> $ python3 -c "import bminf;print(bminf.__version__)"
> ```

0.0.3

**Comment by Hansen06** [comment]
> ```
> bminf
> ```
升级到了0.04，没这个问题

**Comment by Hansen06** [comment]
> 请提供一下你的 bminf 的版本。
> 
> ```
> $ python3 -c "import bminf;print(bminf.__version__)"
> ```

升级到了0.04，没这个问题了

**Comment by chenpe32cp** [comment]
您好，我也遇到了同样的问题，我们bminf版本已经是0.0.4了，请问该如何解决呢？是否因为我用的vocab.txt有问题？

**Comment by a710128** [comment]
> 
> 
> 您好，我也遇到了同样的问题，我们bminf版本已经是0.0.4了，请问该如何解决呢？是否因为我用的vocab.txt有问题？

最新的版本是0.0.5了，目前工具包的接口还不太稳定。
